// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khptnbkddrrfxrekyqth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtocHRuYmtkZHJyZnhyZWt5cXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMDE3NzYsImV4cCI6MjA1NjU3Nzc3Nn0.NunloVLvewqqLCxVvdGC1fPAXUaHsPapy98g5vyqKqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);